### PR TITLE
store shennagins

### PR DESCRIPTION
**Pull request by nnnolan**
i did some stuff for the store, if you could check it out that would be great since the database is iffy on my mac :p 

notable stuff 
`store.js` moved from /modules to /scripts

everything after line 59 is untested store stuff, including some funky copilot suggestions

`db_client.query("UPDATE user_profiles SET points = $1 WHERE Username = $2", [remainingPoints, user], (err, res) => {`  the point changes

`db_client.query("INSERT INTO user_inventory (Username, ItemID) VALUES ($1, $2)", [user, cartItems], (err, res) => {` insert user stuff into a table called `user_inventory` (do we have to initiate this table? or is it created automatically?)`

`  db_client.query("SELECT * FROM user_profiles WHERE Username = $1", [user], function(err, res) {` get the user's points, and dispalys on the page on the div id = "Points", completely untested

### CODE REVIEW

**Comment by NatFletch** [comment]
Yeah sorry ive had no time since last night to check it out. I will when i get home.

**Comment by nnnolan** [comment]
no rush

**Comment by nnnolan** [comment]
forgot to make the function call upon clicking the checkout button lol

**Comment by NatFletch** [comment]
Done

**Pull request merged**
